### ISSUE TITLE
When chuck norris commits, his pushes are a force.

### ISSUE THREAD

**Issue by nothingismagick** [fkromer/taunorris#1]
😂 What a great project. Feel free to close this issue after you have submitted your finished app to the tauri hall of fame.

**Comment by fkromer** [comment]
![chuck-norris-dancing](https://user-images.githubusercontent.com/10199742/122684388-6a003500-d205-11eb-8992-6e972bd696a0.gif) As long as I work alone on a project I love force commits :smiling_imp: :scream: :innocent: Thanks a lot. It has just been a super fast project to try out Tauri with Vue.js 3 and I won't put more effort into it probably. However in any case I love to merge PRs and put it into the hall of fame as soon as it's state is "sufficient"

**Comment by fkromer** [comment]
@nothingismagick Chuck Norris has been active again 😏 [v0.1.0](https://github.com/fkromer/taunorris/releases/tag/v0.1.0)

**Comment by fkromer** [comment]
https://github.com/tauri-apps/tauri-docs/pull/236
